// Code generated by MockGen. DO NOT EDIT.
// Source: internal/ports/ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/ports/ports.go -destination=internal/mocks/mock_ports.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/mariosoaresreis/go-ledger-query/internal/domain"
	ports "github.com/mariosoaresreis/go-ledger-query/internal/ports"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockQueryService) GetBalance(ctx context.Context, accountID uuid.UUID) (*domain.BalanceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(*domain.BalanceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockQueryServiceMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockQueryService)(nil).GetBalance), ctx, accountID)
}

// GetTransaction mocks base method.
func (m *MockQueryService) GetTransaction(ctx context.Context, txID uuid.UUID) (*domain.TransactionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txID)
	ret0, _ := ret[0].(*domain.TransactionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockQueryServiceMockRecorder) GetTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockQueryService)(nil).GetTransaction), ctx, txID)
}

// ListEntries mocks base method.
func (m *MockQueryService) ListEntries(ctx context.Context, q ports.ListEntriesQuery) (*domain.Page[domain.LedgerEntryView], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, q)
	ret0, _ := ret[0].(*domain.Page[domain.LedgerEntryView])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockQueryServiceMockRecorder) ListEntries(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockQueryService)(nil).ListEntries), ctx, q)
}

// ListTransactions mocks base method.
func (m *MockQueryService) ListTransactions(ctx context.Context, q ports.ListTransactionsQuery) (*domain.Page[domain.TransactionView], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, q)
	ret0, _ := ret[0].(*domain.Page[domain.TransactionView])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockQueryServiceMockRecorder) ListTransactions(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockQueryService)(nil).ListTransactions), ctx, q)
}

// MockReadRepository is a mock of ReadRepository interface.
type MockReadRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReadRepositoryMockRecorder
}

// MockReadRepositoryMockRecorder is the mock recorder for MockReadRepository.
type MockReadRepositoryMockRecorder struct {
	mock *MockReadRepository
}

// NewMockReadRepository creates a new mock instance.
func NewMockReadRepository(ctrl *gomock.Controller) *MockReadRepository {
	mock := &MockReadRepository{ctrl: ctrl}
	mock.recorder = &MockReadRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadRepository) EXPECT() *MockReadRepositoryMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockReadRepository) GetBalance(ctx context.Context, accountID uuid.UUID) (*domain.BalanceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(*domain.BalanceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockReadRepositoryMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockReadRepository)(nil).GetBalance), ctx, accountID)
}

// GetTransaction mocks base method.
func (m *MockReadRepository) GetTransaction(ctx context.Context, txID uuid.UUID) (*domain.TransactionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txID)
	ret0, _ := ret[0].(*domain.TransactionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockReadRepositoryMockRecorder) GetTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockReadRepository)(nil).GetTransaction), ctx, txID)
}

// ListEntries mocks base method.
func (m *MockReadRepository) ListEntries(ctx context.Context, q ports.ListEntriesQuery) ([]domain.LedgerEntryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, q)
	ret0, _ := ret[0].([]domain.LedgerEntryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockReadRepositoryMockRecorder) ListEntries(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockReadRepository)(nil).ListEntries), ctx, q)
}

// ListTransactions mocks base method.
func (m *MockReadRepository) ListTransactions(ctx context.Context, q ports.ListTransactionsQuery) ([]domain.TransactionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, q)
	ret0, _ := ret[0].([]domain.TransactionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockReadRepositoryMockRecorder) ListTransactions(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockReadRepository)(nil).ListTransactions), ctx, q)
}

// UpsertBalance mocks base method.
func (m *MockReadRepository) UpsertBalance(ctx context.Context, v *domain.BalanceView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBalance", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBalance indicates an expected call of UpsertBalance.
func (mr *MockReadRepositoryMockRecorder) UpsertBalance(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBalance", reflect.TypeOf((*MockReadRepository)(nil).UpsertBalance), ctx, v)
}

// UpsertEntry mocks base method.
func (m *MockReadRepository) UpsertEntry(ctx context.Context, v *domain.LedgerEntryView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEntry", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEntry indicates an expected call of UpsertEntry.
func (mr *MockReadRepositoryMockRecorder) UpsertEntry(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEntry", reflect.TypeOf((*MockReadRepository)(nil).UpsertEntry), ctx, v)
}

// UpsertTransaction mocks base method.
func (m *MockReadRepository) UpsertTransaction(ctx context.Context, v *domain.TransactionView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTransaction", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTransaction indicates an expected call of UpsertTransaction.
func (mr *MockReadRepositoryMockRecorder) UpsertTransaction(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTransaction", reflect.TypeOf((*MockReadRepository)(nil).UpsertTransaction), ctx, v)
}

// MockTransactor is a mock of Transactor interface.
type MockTransactor struct {
	ctrl     *gomock.Controller
	recorder *MockTransactorMockRecorder
}

// MockTransactorMockRecorder is the mock recorder for MockTransactor.
type MockTransactorMockRecorder struct {
	mock *MockTransactor
}

// NewMockTransactor creates a new mock instance.
func NewMockTransactor(ctrl *gomock.Controller) *MockTransactor {
	mock := &MockTransactor{ctrl: ctrl}
	mock.recorder = &MockTransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactor) EXPECT() *MockTransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockTransactor) RunInTx(ctx context.Context, fn func(ports.ReadRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockTransactorMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockTransactor)(nil).RunInTx), ctx, fn)
}

// MockProjectionStore is a mock of ProjectionStore interface.
type MockProjectionStore struct {
	ctrl     *gomock.Controller
	recorder *MockProjectionStoreMockRecorder
}

// MockProjectionStoreMockRecorder is the mock recorder for MockProjectionStore.
type MockProjectionStoreMockRecorder struct {
	mock *MockProjectionStore
}

// NewMockProjectionStore creates a new mock instance.
func NewMockProjectionStore(ctrl *gomock.Controller) *MockProjectionStore {
	mock := &MockProjectionStore{ctrl: ctrl}
	mock.recorder = &MockProjectionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectionStore) EXPECT() *MockProjectionStoreMockRecorder {
	return m.recorder
}

// GetBalance mocks base method.
func (m *MockProjectionStore) GetBalance(ctx context.Context, accountID uuid.UUID) (*domain.BalanceView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(*domain.BalanceView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockProjectionStoreMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockProjectionStore)(nil).GetBalance), ctx, accountID)
}

// GetTransaction mocks base method.
func (m *MockProjectionStore) GetTransaction(ctx context.Context, txID uuid.UUID) (*domain.TransactionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, txID)
	ret0, _ := ret[0].(*domain.TransactionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockProjectionStoreMockRecorder) GetTransaction(ctx, txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockProjectionStore)(nil).GetTransaction), ctx, txID)
}

// ListEntries mocks base method.
func (m *MockProjectionStore) ListEntries(ctx context.Context, q ports.ListEntriesQuery) ([]domain.LedgerEntryView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", ctx, q)
	ret0, _ := ret[0].([]domain.LedgerEntryView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockProjectionStoreMockRecorder) ListEntries(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockProjectionStore)(nil).ListEntries), ctx, q)
}

// ListTransactions mocks base method.
func (m *MockProjectionStore) ListTransactions(ctx context.Context, q ports.ListTransactionsQuery) ([]domain.TransactionView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, q)
	ret0, _ := ret[0].([]domain.TransactionView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockProjectionStoreMockRecorder) ListTransactions(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockProjectionStore)(nil).ListTransactions), ctx, q)
}

// RunInTx mocks base method.
func (m *MockProjectionStore) RunInTx(ctx context.Context, fn func(ports.ReadRepository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockProjectionStoreMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockProjectionStore)(nil).RunInTx), ctx, fn)
}

// UpsertBalance mocks base method.
func (m *MockProjectionStore) UpsertBalance(ctx context.Context, v *domain.BalanceView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBalance", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBalance indicates an expected call of UpsertBalance.
func (mr *MockProjectionStoreMockRecorder) UpsertBalance(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBalance", reflect.TypeOf((*MockProjectionStore)(nil).UpsertBalance), ctx, v)
}

// UpsertEntry mocks base method.
func (m *MockProjectionStore) UpsertEntry(ctx context.Context, v *domain.LedgerEntryView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertEntry", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertEntry indicates an expected call of UpsertEntry.
func (mr *MockProjectionStoreMockRecorder) UpsertEntry(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEntry", reflect.TypeOf((*MockProjectionStore)(nil).UpsertEntry), ctx, v)
}

// UpsertTransaction mocks base method.
func (m *MockProjectionStore) UpsertTransaction(ctx context.Context, v *domain.TransactionView) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertTransaction", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertTransaction indicates an expected call of UpsertTransaction.
func (mr *MockProjectionStoreMockRecorder) UpsertTransaction(ctx, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertTransaction", reflect.TypeOf((*MockProjectionStore)(nil).UpsertTransaction), ctx, v)
}

// MockEventDispatcher is a mock of EventDispatcher interface.
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatcherMockRecorder
}

// MockEventDispatcherMockRecorder is the mock recorder for MockEventDispatcher.
type MockEventDispatcherMockRecorder struct {
	mock *MockEventDispatcher
}

// NewMockEventDispatcher creates a new mock instance.
func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatcher) EXPECT() *MockEventDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockEventDispatcher) Dispatch(ctx context.Context, env domain.Envelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dispatch", ctx, env)
	ret0, _ := ret[0].(error)
	return ret0
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockEventDispatcherMockRecorder) Dispatch(ctx, env any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockEventDispatcher)(nil).Dispatch), ctx, env)
}
